### ISSUE TITLE
Hard-coded cache location

### ISSUE THREAD

**Issue by ghoseb** [nshan651/excite-cli#5]
Thanks for `excite`, I am "excited" about it :-)

While looking at the code I found that the HTTP cache path is currently hard-coded. Not sure if that will work as intended on other computers.

We may want to factor it out to a stable path in `/tmp` (probably suffixed with `excite` version).

These are the places where I found the cache path being used - 

https://github.com/nshan651/excite/blob/d03e19042ff8dc6265be95de8de9972cbfd6337d/src/api.lua#L45
https://github.com/nshan651/excite/blob/d03e19042ff8dc6265be95de8de9972cbfd6337d/src/api.lua#L65

**Comment by nshan651** [comment]
Hi, thank you for the suggestion! I agree that those two example should go in /tmp, I will change that to make it more compatible. 

However, I'm running into another issue that I could use some help with. My plan for now is to execute the lua modules from a script that's added to the path. What I can't figure out is how to source my lua modules so that they can be run regardless of where the script or /src folder is located.

**Comment by nshan651** [comment]
I fixed the links to be more location-agnostic and figured out the module sourcing issue, two birds with one stone!
https://github.com/nshan651/excite/blob/5ca3192b7081dd3bfa58b72df3c0eb14ced7b46f/src/api.lua#L46
https://github.com/nshan651/excite/blob/5e67b9dd86c3d4d33815aa14ce4c0a3654bdc751/src/api.lua#L66

To allow the script to run the `/src` package from anywhere (e.g /usr/share/bin), I updated the package.path variable to search the project directory. 
https://github.com/nshan651/excite/blob/5ca3192b7081dd3bfa58b72df3c0eb14ced7b46f/src/excite.lua#L25-L36

I added a wildcard in the path link so it can be located anywhere in a user's home directory. This link is then passed to `excite.lua` as an argument.
https://github.com/nshan651/excite/blob/9712c8b1ef2beb3995e647ad43e11f991abff463/excite#L15-L16

This definitely isn't the cleanest solution. I'm going to mark this as closed for now, but anyone can feel free to raise another issue/submit a PR with a better fix.
